title = "MaxiCode"
baseURL = 'https://hba.sid.one/'

# This is what goes in <html lang="">
languageCode = 'es'

theme = "hugo-blog-awesome"

# This defines how dates are formatted
defaultContentLanguage = "es"

# To enable Google Analytics 4 (gtag.js) provide G-MEASUREMENT_ID below.
# To disable Google Analytics, simply leave the field empty or remove the next line
googleAnalytics = 'G-NN0TQ469BP' # G-MEASUREMENT_ID

# Enable emojis globally
enableEmoji = true
ignoreErrors = ["additional-script-loading-error"] # ignore error of loading additional scripts.

# To enable Disqus comments, provide Disqus Shortname below.
# To disable Disqus comments, simply leave the field empty or remove the next line
disqusShortname = ''

# set markup.highlight.noClasses=false to enable code highlight
[markup]
  [markup.highlight]
    noClasses = false
  [markup.goldmark.renderer]
    unsafe = true
	[markup.tableOfContents]
		startLevel = 2 # ToC starts from H2
		endLevel = 4 # ToC ends at H4
		ordered = false # generates <ul> instead of <ol>

############################## Idioma Español ################################
[Languages.es]
  languageName = "Español"
  languageCode = "es"
  contentDir = "content/es"
  weight = 2

  [Languages.es.menu]
  [[Languages.es.menu.main]]
    # La referencia de la página (pageRef) es útil para resaltar el menú
    # Cuando pageRef está configurado, establecer `url` es opcional; se utilizará como un valor de reserva si la página no se encuentra.
    pageRef="/"
    name = 'Inicio'
    url = '/'
    weight = 10
  [[Languages.es.menu.main]]
    pageRef="entradas"
    name = 'Entradas'
    url = '/entradas/'
    weight = 20
  [[Languages.es.menu.main]]
    pageRef="about"
    name = 'Acerca de'
    url = '/about/'
    weight = 30

[Languages.es.params]
  sitename = "Libertad-Digital"
  defaultColor = "dark" # establecer modo de color: dark, light, auto
  # Establecerlo en 'auto' aplica el esquema de color según la preferencia de color del dispositivo del visitante. Si no especificas nada, ignora este parámetro o déjalo en blanco,
  # el valor predeterminado se establece en 'auto'.
  # Puedes consultar layouts/index.html para obtener más información.
  description = "Tema de blog Hugo minimalista con soporte para modo claro y oscuro"
  mainSections = ['entradas']
  toc = true # establecer en false para desactivar la tabla de contenido 'globalmente'
  tocOpen = false # establecer en true para abrir la tabla de contenido de forma predeterminada
  goToTop = true # establecer en false para desactivar el botón 'ir arriba'
  additionalScripts = ['js/custom.js', 'js/custom-2.js']
  # Intentará cargar 'assets/js/custom.js' y 'assets/js/custom-2.js'.
  # Tus scripts personalizados se concatenarán en un archivo `custom.js`.
  # Al construir para producción, se minimizará.
  # El archivo `custom.js` se carga en cada página (antes de que termine la etiqueta body).
  dateFormat = "" # formato de fecha utilizado para mostrar fechas en varias páginas. Si no se especifica nada, se utiliza el formato "2 Jan 2006".
  # Ver https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference para conocer los formatos de fecha disponibles.
  rssFeedDescription = "summary" # opciones disponibles: 1) summary 2) full
  # resumen - incluye un breve resumen de la entrada de blog en el feed RSS. Generado usando Hugo .Summary .
  # completo - incluye la entrada completa de blog en el feed RSS. Generado usando Hugo .Content .
  # Por defecto (o si no se especifica nada), se utiliza el resumen.

[Languages.es.params.author]
  avatar = "avatar.jpg" # coloca el archivo en la carpeta assets; también asegúrate de que la imagen tenga la misma altura y anchura
  # Nota: la imagen no se renderiza si no se encuentra el recurso (imagen de avatar). No se muestra ningún error.
  intro = "MaxiCode"
  name = "Maxi"
  description = "Libertad Digital"

# Permitir anular opciones de manifiesto web
[Languages.es.params.webmanifest]
  name = "sitename" # utilizará "params.sitename" o "title" por defecto
  short_name = "sitename" # igual que name
  start_url = "/" # utilizará la URL de la página de inicio por defecto
  theme_color = "#434648" # por defecto es "#434648" (color base del texto). También anulará `<meta name="theme-color" />`
  background_color = "#fff" # por defecto depende de "params.defaultColor" para "light" o "auto" se establecerá en "#fff" para dark se establecerá en "#131418" (color de fondo del modo oscuro)
  display = "standalone"


############################## English language ################################
[Languages.en-gb]
  languageName = "English"
  languageCode = "en-gb"
  contentDir = "content/en"
  weight = 1

  [Languages.en-gb.menu]
  [[Languages.en-gb.menu.main]]
    # The page reference (pageRef) is useful for menu highlighting
    # When pageRef is set, setting `url` is optional; it will be used as a fallback if the page is not found.
    pageRef="/"
    name = 'Home'
    url = '/'
    weight = 10
  [[Languages.en-gb.menu.main]]
    pageRef="posts"
    name = 'Posts'
    url = '/posts/'
    weight = 20
  [[Languages.en-gb.menu.main]]
    pageRef="about"
    name = 'About'
    url = '/about/'
    weight = 30

[Languages.en-gb.params]
  sitename = "Libertad-Digital"
  defaultColor = "dark" # set color mode: dark, light, auto
  # Setting it to 'auto' applies the color scheme based on the visitor's device color preference.If you don't specify anything, ignore this parameter, or leave it blank,
  # the default value is set to 'auto'.
  # You can take a look at layouts/index.html for more information.
  description = "Minimal Hugo blog theme with light and dark mode support"
  mainSections = ['posts']
  toc = true # set to false to disable table of contents 'globally'
  tocOpen = false # set to true to open table of contents by default
  goToTop = true # set to false to disable 'go to top' button
  additionalScripts = ['js/custom.js', 'js/custom-2.js']
  # Will try to load 'assets/js/custom.js' and 'assets/js/custom-2.js'.
  # Your custom scripts will be concatinated to one file `custom.js`.
  # When building for production it will be minified.
  # The file `custom.js` is loaded on each page (before body tag ends).
  dateFormat = "" # date format used to show dates on various pages. If nothing is specified, then "2 Jan 2006" format is used.
  # See https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference for available date formats.
  rssFeedDescription = "summary" # available options: 1) summary 2) full
  # summary - includes a short summary of the blog post in the RSS feed. Generated using Hugo .Summary .
  # full - includes full blog post in the RSS feed. Generated using Hugo .Content .
  # By default (or if nothing is specified), summary is used.

[Languages.en-gb.params.author]
  avatar = "avatar.jpg" # put the file in assets folder; also ensure that image has same height and width
  # Note: image is not rendered if the resource(avatar image) is not found. No error is displayed.
  intro = "Libertad Digital"
  name = "Maxi"
  description = "101101010001101101011"

# Allow to override webmanifest options
[Languages.en-gb.params.webmanifest]
  name = "sitename" # will use "params.sitename" or "title" by default
  short_name = "sitename" # same as name
  start_url = "/" # will use homepage url by default
  theme_color = "#434648" # default is "#434648" (base color of text). Also will override html `<meta name="theme-color" />`
  background_color = "#fff" # by default depend on "params.defaultColor" for "light" or "auto" will be set to "#fff" for dark will be "#131418" (color of dark mode background)
  display = "standalone"

###################################################################

# Allow to override `browserconfig.xml` params (configuration for windows embeded browsers)
[params.browserconfig]
  TileColor = "#2d89ef" # default windows 10 blue tile color

[[params.socialIcons]]
name = "github"
url = "https://github.com/ottino"

[[params.socialIcons]]
name = "twitter"
url = "https://twitter.com/ottinomax"

[[params.socialIcons]]
name = "Rss"
url = "index.xml"
